# config/config.yaml

persist_directory: "./chroma_db"
descriptions_file: "./index_descriptions.json"

chunking:
  chunk_size: 256
  chunk_overlap: 64
  breakpoint_threshold_amount: 0.15
  breakpoint_threshold_type: "percentile"

retrieval:
  coarse_top_k: 10
  rerank_top_k: 5

embedding_model: "nomic-ai/nomic-embed-text-v2-moe"

llm:
  default_model: "llama3"
  available_models:
    - llama3
    - nemotron
    - guanaco
    - vicuna

logging:
  #level: "INFO"
  level: "DEBUG"

environment:
  tokenizers_parallelism: false
